name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.1'

      # 3. Generate .env file
      - name: Generate .env file
        working-directory: ./ssafyhome_front
        run: |
          echo "VITE_OPEN_API_SERVICE_KEY=${{ secrets.VITE_OPEN_API_SERVICE_KEY }}" >> .env
          echo "VITE_KAKAO_MAP_SERVICE_KEY=${{ secrets.VITE_KAKAO_MAP_SERVICE_KEY }}" >> .env
          echo "VITE_VUE_API_URL=${{ secrets.VITE_VUE_API_URL }}" >> .env
          echo "VITE_KAKAO_REST_API_KEY=${{ secrets.VITE_KAKAO_REST_API_KEY }}" >> .env
          echo "VITE_KAKAO_REDIRECT_URI=${{ secrets.VITE_KAKAO_REDIRECT_URI }}" >> .env
          echo "VITE_KAKAO_CLIENT_SECRET=${{ secrets.VITE_KAKAO_CLIENT_SECRET }}" >> .env
          echo "VITE_ARTICLE_LIST_SIZE=${{ secrets.VITE_ARTICLE_LIST_SIZE }}" >> .env
          echo "VITE_ARTICLE_NAVIGATION_SIZE=${{ secrets.VITE_ARTICLE_NAVIGATION_SIZE }}" >> .env

      # 4. Install dependencies
      - name: Install dependencies
        working-directory: ./ssafyhome_front
        run: npm ci

      # 5. Build the Vue.js application
      - name: Build Vue.js Application
        working-directory: ./ssafyhome_front
        run: npm run build

      # 6. Deploy to Azure Static Web Apps
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_MOSS_0E91D2D00 }}
          action: "upload"
          app_location: "./ssafyhome_front"
          output_location: "dist" # 빌드 결과물 경로
