name: Deploy Spring Boot Backend to Azure

on:
  push:
    branches:
      - main  # 메인 브랜치 변경 시 실행

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      # 코드 가져오기
      - name: Checkout code
        uses: actions/checkout@v3

      # Java 환경 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Maven 빌드
      - name: Build Spring Boot Application
        working-directory: ./ssafyhome_back
        run: mvn clean package

      # Azure App Service로 배포
      - name: Deploy to Azure App Service (Backend)
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME_BACK }}
          publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
          package: ssafyhome_back/target/*.jar
